proxy:
    listen:
        address: "0.0.0.0"
        port: 8080  
    services:
      - name: nick-service
        domain: service.ofnick.com
        hosts:
          - address: "http://backend1"
            port: 80
          - address: "http://backend2"
            port: 80
          - address: "http://backend3"
            port: 80
          - address: "http://backend4"
            port: 80
          - address: "http://backend5"
            port: 80
